### PR TITLE
Allow for :memory: sqlite3 path - useful for testing

### PR DESCRIPTION
**Pull request by mtai**
Hey Jason, long time no see :)

We're using sqlite3dbm extensively here at Adku and we needed to create a temporary sqlite3map for testing purposes.  To make a throw-away sqlite3map that we can also populate on the fly (think fixtures), we patched in support for the special sqlite3 ":memory:" path.  Hope you guys find this useful too :)

-Matt

### CODE REVIEW

**Comment by jfennell** [comment]
Hey Matt!  Long time no see indeed. ^_^

So, my approach to testing on sqlite3dbm itself was to have a test case that created & and destroyed a temporary directory to store the sqlite3dbm in.  If you're doing testing, is there a reason you can't use that approach?  I'm a bit hesitant to modify the **init** such that the main path is all hidden behind a conditional and it looks like the main path is ':memory:' when the main point of sqlite3dbm is on-disk persistence.

Another approach is:
import os
import shutil
import tempfile
from contextlib import contextmanager

import sqlite3dbm

@contextmanager
def temporary_sqlite3dbm():
    tmpdir = tempfile.mkdtemp()
    path = os.path.join(tmpdir, 'temporary_db.sqlite')
    smap = sqlite3dbm.open(path, 'c')
    yield smap
    shutil.rmtree(tmpdir)

if **name** == '**main**':
    with temporary_sqlite3dbm() as db:
        db['foo'] = 'bar'
        print db.items()

thoughts?

**Comment by jfennell** [comment]
Sorry, didn't mean to close the pull request :-P

**Comment by mtai** [comment]
Ah I meant to say the issue was less about testing but more about supporting an existing SQLite pattern.

http://www.sqlite.org/inmemorydb.html

It just happens to be that we use the in-memory db for testing purposes.  If you pass ":memory:" into sqlite3dbm, you get a messed up path and a persisted dictionary when I would've expected it to follow SQLite's defined behavior.

**Comment by jfennell** [comment]
So, I actually meant to pull this into development, not master (sorry, first pull request :-/).  I've done a little bit of evil history rewriting and remove this from master (I doubt that anybody got mixed up in those few minutes ^_^).

So, end result: this was merged into development by hand and I also added a couple of tests to make sure it behaves right.

When I'm ready for another release I'll merge these into master and everything will be hunky dory.

Thanks again for the patch, and sorry this took so long to resolve!

**Comment by mtai** [comment]
Sure no problem, thanks for accepting the patch!

**Pull request merged**
